### ISSUE TITLE
Amplify Update Attributes

### ISSUE THREAD

**Issue by KLU01** [bvillaroman/UniDesignCompassApp#112]
There is an issue with updating the user attributes. I have tried using
```javascript
let user = Auth.currentAuthenticatedUser();
Auth.updateUserAttributes(user, {attribute: value});
```
I receive the error of an Unhandled promise rejection and occasionally an error of a nonexisting attribute. 

So when I try to print out the user attributes using
```javascript
Auth.userAttributes(user);
```
The attributes i'm trying to update do not exist UNLESS I try
```javascript
Auth.currentUserInfo();
```
I'm not sure if this has anything to do with maping identity provider attributes to user pool attributes?

**Comment by rdiaz002** [comment]
Ill look over this
