### ISSUE TITLE
User Attributes Check

### ISSUE THREAD

**Issue by KLU01** [bvillaroman/UniDesignCompassApp#115]
Is there a method one of you pre-wrote to ensure the user enters a proper email or phone number, especially for the signup pages? I don't want to create one myself if one of you did it already. (This is for the general settings page).

Let me know!

**Comment by rdiaz002** [comment]
Amplify handles that. If a phone number isnt properly formatted it will reject the request and it should do the same with the email. All that needs to be done is to catch the error and display it in the front end.

**Comment by KLU01** [comment]
I log the error, but an error is only detected when the number =< +123
