### ISSUE TITLE
create analytics page that records history of logs of phases

### ISSUE THREAD

**Issue by bvillaroman** [bvillaroman/UniDesignCompassApp#54]

**Comment by ramonpetgrave64** [comment]
Partially done with #98

**Comment by ramonpetgrave64** [comment]
Nearly complete with #118.

Now need to display hh:mm:ss on the barchart, reather than time in milliseconds.

**Comment by ramonpetgrave64** [comment]
More improvements with #139. Plot's hours instead of milliseconds.
Still no hh:mm:ss.
